<a href="https://colab.research.google.com/github/aliatulmaryani/uas-data-base/blob/main/Siti_Aliatul_Maryani_I_2310354_Tugas_pertemuan_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MECHINE LEARNING**

# **TUGAS 1**

In [16]:
#load data
from sklearn.datasets import load_iris
iris_datasets = load_iris()


In [17]:
print("Jenis isian dataset iris =\n {}".format(iris_datasets.keys()))

Jenis isian dataset iris =
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [18]:
print ("Target Name = {}".format(iris_datasets['target_names']))

Target Name = ['setosa' 'versicolor' 'virginica']


In [19]:
print("Target Name = {}".format(iris_datasets['target']))

Target Name = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
print("Feature Name = {}".format(iris_datasets['feature_names']))

Feature Name = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [21]:
print("Data = {}".format(iris_datasets['data']))
print("Ukuran data = {}".format(iris_datasets['target'].shape))

Data = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9

In [22]:
from sklearn.model_selection import train_test_split
data = iris_datasets['data']
target = iris_datasets['target']

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.15, random_state = 0)

In [23]:
print("Jumlah data x training =" ,x_train.shape)
print("Jumlah data x testing =" ,x_test.shape)
print("Jumlah data y training =" ,y_train.shape)
print("Jumlah data y testing =" ,y_test.shape)

Jumlah data x training = (127, 4)
Jumlah data x testing = (23, 4)
Jumlah data y training = (127,)
Jumlah data y testing = (23,)


In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [25]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [26]:
import numpy as np
x_baru = np.array([[3, 5.1, 5, 4.2]])
prediksi = knn.predict(x_baru)
print("Hasil Prediksi KNN =" ,prediksi)

Hasil Prediksi KNN = [2]


In [27]:
x_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2]])

In [28]:
prediksi1 = knn.predict(x_test)
print("Hasil prediksi x_test =", prediksi1)

Hasil prediksi x_test = [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0]


In [29]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0])

In [30]:
from sklearn.metrics import accuracy_score

print("Hasil Akurasi = ", accuracy_score(y_test, prediksi1) * 100)


Hasil Akurasi =  100.0


# **TUGAS 2**

In [31]:
from sklearn.model_selection import train_test_split
data = iris_datasets['data']
target = iris_datasets['target']

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.255, random_state = 0)

In [32]:
print("Jumlah data x training =" ,x_train.shape)
print("Jumlah data x testing =" ,x_test.shape)
print("Jumlah data y training =" ,y_train.shape)
print("Jumlah data y testing =" ,y_test.shape)

Jumlah data x training = (111, 4)
Jumlah data x testing = (39, 4)
Jumlah data y training = (111,)
Jumlah data y testing = (39,)


In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [34]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [35]:
import numpy as np
x_baru = np.array([[3, 5.1, 5, 4.2]])
prediksi = knn.predict(x_baru)
print("Hasil Prediksi KNN =" ,prediksi)

Hasil Prediksi KNN = [2]


In [36]:
x_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [37]:
prediksi1 = knn.predict(x_test)
print("Hasil prediksi x_test =", prediksi1)


Hasil prediksi x_test = [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1]


In [38]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1])

In [39]:
from sklearn.metrics import accuracy_score

print("Hasil Akurasi = ", accuracy_score(y_test, prediksi1) * 100)


Hasil Akurasi =  97.43589743589743


# TUGAS **3**

In [41]:
from sklearn.model_selection import train_test_split
data = iris_datasets['data']
target = iris_datasets['target']

x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.3125, random_state = 0)

In [42]:
print("Jumlah data x training =" ,x_train.shape)
print("Jumlah data x testing =" ,x_test.shape)
print("Jumlah data y training =" ,y_train.shape)
print("Jumlah data y testing =" ,y_test.shape)

Jumlah data x training = (103, 4)
Jumlah data x testing = (47, 4)
Jumlah data y training = (103,)
Jumlah data y testing = (47,)


In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [44]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [45]:
import numpy as np
x_baru = np.array([[3, 5.1, 5, 4.2]])
prediksi = knn.predict(x_baru)
print("Hasil Prediksi KNN =" ,prediksi)

Hasil Prediksi KNN = [2]


In [46]:
x_test

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [47]:
prediksi1 = knn.predict(x_test)
print("Hasil prediksi x_test =", prediksi1)

Hasil prediksi x_test = [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2 1 1 2 0 2 0 0 1 2]


In [48]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2])

In [49]:
from sklearn.metrics import accuracy_score

print("Hasil Akurasi = ", accuracy_score(y_test, prediksi1) * 100)


Hasil Akurasi =  97.87234042553192
